#!/usr/bin/env python3

f=open("2FA9noend.pdb")
print(f.read())

import sys

pdbfile=sys.argv[1]
f= open(pdbfile, 'r')
lines=f.readlines()
list=[]

for line in lines:
	words=line.split()
	list.append(words)
print(list)
f.close()
print ("Done!")
sys.exit 

#****************************************
import sys

for line in lines:
	words = line.split()
	list.append(words)  
	f.close()

Statement= input("Do you want to input coordinates (Otherwise, the Center of Mass will be used) [y/n]?")
if Statement =='y':
  x_C = float(input("Enter x:"))
  y_C = float(input("Enter y:"))
  z_C = float(input("Enter z:"))
  
else: 
  Sm = 0
  Smx = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12
    if atom[-1]== 'O':
      m = 16
    if atom[-1]== 'N':
      m = 14
    if atom[-1] =='H':
      m = 1.01
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'Mg':
      m = 24.30
    Sm = Sm + m
    x = float(atom[6])
    Smx = Smx + m*x
  x_C = Smx/Sm
  
  Sm = 0
  Smy = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12
    if atom[-1]== 'O':
      m = 16
    if atom[-1]== 'N':
      m = 14
    if atom [-1] == 'H':
      m = 1.01
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'Mg':
      m = 24.30
    Sm = Sm + m
    y = float(atom[7])
    Smy = Smy + m*y
  y_C = Smy/Sm
  
  Sm = 0
  Smz = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12.01
    if atom[-1]== 'N':
      m = 14.01
    if atom[-1]== 'O':
      m = 16.0
    if atom[-1] == 'H':
      m = 1.01
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'Mg':
      m = 24.30
    Sm = Sm + m
    z = float(atom[8])
    Smz = Smz + m*z
  z_C = Smz/Sm




fout = open("output.pdb",'w')
for atom in list:
  x = float(atom[6]) - x_C
  y = float(atom[7]) - y_C
  z = float(atom[8]) - z_C
  OC = "{:6.2f}".format(float(atom[9]))
  TMP= "{:6.2f}".format(float(atom[10]))
  line = '%s %6s  %-3s %s %s%4s %s%s%s%s%s%12s\n' %(atom[0],atom[1],atom[2],atom[3],atom[4],atom[5],"{:11.3f}".format(x),"{:8.3f}".format(y),"{:8.3f}".format(z),OC,TMP,atom[11])
  fout.write(line)

fout.close()
sys.exit