#!/usr/bin/env python3

import sys


pdbname=sys.argv[1]

f = open(pdbname, 'r')
lines = f.readlines()

list = []

for l in lines:

  words = l.split()
  list.append(words) 

print(list) 
f.close()
print("Done!")

#*************************************

Statement= input("Do you want to calculate the center by mass or geometry [m/g]:")
if Statement =='g':
  i = 0
  sumx = 0
  sumy = 0
  sumz = 0
  for atom in list:
    x = float(atom[6])
    y = float(atom[7])
    z = float(atom[8])
    sumx = sumx + x
    sumy = sumy + y
    sumz = sumz + z
    i = i+1

  x_C = sumx/i
  y_C = sumy/i
  z_C = sumz/i
    

else: 
#sigma mixi / sigma mi
  sm = 0
  smx = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12.01
    if atom[-1]== 'N':
      m = 14.00
    if atom[-1]== 'O':
      m = 15.99
    if atom[-1] == 'H':
      m = 1.00
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'MG':
      m = 24.30
    sm = sm + m
    x = float(atom[6])
    smx = smx + m*x

  x_C = smx/sm
  
  sm = 0
  smy = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12.01
    if atom[-1]== 'N':
      m = 14.01
    if atom[-1]== 'O':
      m = 16.0
    if atom[-1] == 'H':
      m = 1.01
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'MG':
      m = 24.30
    sm = sm + m
    y = float(atom[7])
    smy = smy + m*y

  y_C = smy/sm
  
  sm = 0
  smz = 0
  for atom in list:
    if atom[-1] == 'C':
      m = 12.01
    if atom[-1]== 'N':
      m = 14.01
    if atom[-1]== 'O':
      m = 16.0
    if atom[-1] == 'H':
      m = 1.01
    if atom[-1] == 'S':
      m = 32.07
    if atom[-1] == 'P':
      m = 30.97
    if atom[-1] == 'MG':
      m = 24.30
    sm = sm + m
    z = float(atom[8])
    smz = smz + m*z

  z_C = smz/sm

#**********************************************

fout = open("output.pdb",'w')
for atom in list:
  x = float(atom[6]) - x_C
  y = float(atom[7]) - y_C
  z = float(atom[8]) - z_C
  OCC = "{:6.2f}".format(float(atom[9]))
  Temp= "{:6.2f}".format(float(atom[10]))
  line = '%s %6s  %-3s %s %s%4s %s%s%s%s%s%12s\n' %(atom[0],atom[1],atom[2],atom[3],atom[4],atom[5],"{:11.3f}".format(x),"{:8.3f}".format(y),"{:8.3f}".format(z),OCC,Temp,atom[11])
  fout.write(line)

fout.close()
sys.exit()